version: '3.1'

services:
  mysql57:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_example
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      # if you want to initialize data
      # - ./initdb.d:/docker-entrypoint-initdb.d
      # if you want to keep the data in local directory
      # - ./mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
